### ISSUE TITLE
signing in with a username instead of an email address 

### ISSUE THREAD

**Issue by Maay** [jm81/dm-devise#12]
Hi, I'm trying to make my devise app to signing in by username, so I've added 

`````` #initializers/devise.rb
config.authentication_keys = [ :username ]```

``````
# /models/user.rb

class User
  include DataMapper::Resource

  devise :database_authenticatable, :registerable, :lockable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username] 

  property :id, Serial
  property :username, String
  property :email, String
  property :name, String
  property :country, String

```
And have edited views. 
Now it does signing me in with username+password, but during the registration it validates the uniqueness of email, not login. What is the problem, what have I missed?  
```

**Comment by jm81** [comment]
Devise's validatable module is just for validations on the email and password fields (see https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb). I'm not sure it would make sense to have validatable be affected by config.authentication_keys since authentication_keys can use multiple fields (not necessarily unique). For now, you'll need to manually add a uniqueness validation on the username in your model:

```
property :username, String, :unique => true
```

If you don't want the uniqueness of email validated, remove :validatable from the list of devise module and copy the password validations directly into your model:

```
validates_presence_of :password, :if => :password_required?
validates_confirmation_of :password, :if => :password_required?
validates_length_of :password, :within => password_length, :allow_blank => true
```

Does that help?

**Comment by Maay** [comment]
Yup, thank you for the feedback!
